plugins {
    id 'multiloader-loader'
    id 'fabric-loom'
}

repositories {
    maven {
        url = 'https://maven.fabricmc.net'
    }

    maven {
        url = 'https://www.cursemaven.com'
        content {
            includeGroup 'curse.maven'
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"

    mappings loom.layered {
        officialMojangMappings()
        parchment(
                "org.parchmentmc.data:parchment-${parchment_minecraft}:${parchment_version}@zip"
        )
    }

    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"

    compileOnly "mezz.jei:jei-${minecraft_version}-common-api:${jei_version}"
    modLocalRuntime "mezz.jei:jei-${minecraft_version}-fabric:${jei_version}"

    modCompileOnly "curse.maven:just-enough-resources-jer-240630:${jer_fabric_file}"
    modLocalRuntime "curse.maven:just-enough-resources-jer-240630:${jer_fabric_file}"
}

loom {
    log4jConfigs.from file('log4j-dev.xml')

    def aw = project(':common').file(
            "src/main/resources/${mod_id}.accesswidener"
    )

    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }

    mixin {
        defaultRefmapName.set(
                "${mod_id}.refmap.json"
        )
    }

    runs {
        client {
            client()
            displayName = 'Fabric Client'
            generateRunConfig = true
            preferGradleTask = false
            runDirectory = file('runs/client')
        }

        server {
            server()
            displayName = 'Fabric Server'
            generateRunConfig = true
            preferGradleTask = false
            runDirectory = file('runs/server')
        }
    }
}